### ISSUE TITLE
XBMC/UNLEASH X ALWAYS SHOWING BUSY FOR DVD DRIVE

### ISSUE THREAD

**Issue by Supah736** [gaasedelen/titan#11] opened 2022-04-17 22:33 UTC
![image](https://user-images.githubusercontent.com/102563174/163734681-4e5820aa-0028-4f13-9610-683e724e210b.png)
![image](https://user-images.githubusercontent.com/102563174/163734695-5b6e78a4-e53b-4260-a575-6e4ed3521f10.png)
Is this normal running latest titan bios?

**Comment by gaasedelen** [comment] 2022-04-22 21:55
This is going to be a duplicate of your other issue (#7), some DVD drives act weird with large HDD's in the system. It'll be investigated (and hopefully resolved) under #7.

But as I said in the other issue was that I was able to reproduce this behavior under M8+ without ever patching it to use Titan. It's possible the DVD drive is starting to fall out of spec (failing) but will require more investigation.

**Closed as completed by gaasedelen** 2022-04-22 21:55 UTC
